name: Checkov Scan

on:
  workflow_call:
    inputs:
      terraform-roots:
        description: JSON array of terraform roots to scan.
        required: true
        type: string

permissions:
  contents: read
  security-events: write

jobs:

  checkov:
    name: Checkov Scan ${{ matrix.terraform-root }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        terraform-root: ${{ fromJson(inputs.terraform-roots) }}

    defaults:
      run:
        working-directory: ${{ matrix.terraform-root }}

    steps:
      - uses: actions/checkout@v4

      - name: Run Checkov
        uses: bridgecrewio/checkov-action@v12
        with:
          framework: terraform