name: Gitleaks Scan

on:
  workflow_call:

permissions:
  contents: read
  pull-requests: read

jobs:
  scan-secrets:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITLEAKS_GITHUB_TOKEN: ${{ github.token }}
