name: Release

on:
  workflow_call:
    inputs:
      release-type:
        required: false
        default: simple
        type: string
      config-file:
        required: false
        default: release-please-config.json
        type: string
      manifest-file:
        required: false
        default: .release-please-manifest.json
        type: string
    outputs:
      release-created:
        value: ${{ jobs.release.outputs.release-created }}
      tag-name:
        value: ${{ jobs.release.outputs.tag-name }}
    secrets:
      RELEASE_TOKEN:
        required: false

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      release-created: ${{ steps.release.outputs.release_created }}
      tag-name: ${{ steps.release.outputs.tag_name }}
    steps:
      - id: release
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.RELEASE_TOKEN || github.token }}
          release-type: ${{ inputs.release-type }}
          config-file: ${{ inputs.config-file }}
          manifest-file: ${{ inputs.manifest-file }}